missions:
  - echo "starting cingi tests"
  - outpost:
      setup:
        - mix deps.get
        - make build-cli
        - mix test --only nonexistenttag # Only so that dependencies are forced to compile
    missions:
      normal_test: echo "Running mix test for $UUID" && mix test
      distributed_test:
        outpost:
          setup: epmd -daemon
        missions: echo "Running mix distributed test for $UUID" && mix test --only distributed
  - echo "cingi tests successful"
