language: elixir
elixir:
  - 1.5
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install nmap
install:
  - mix local.rebar --force # for Elixir 1.3.0 and up
  - mix local.hex --force
  - mix deps.get
  - mix escript.build
script:
  - ./cingi --file .cingi.yaml
branches:
  only:
    - master
